package studio.rashka.Test;

public class Question4 {

    public StringBuilder[] V4 = new StringBuilder[]{
            new StringBuilder("Угра"),
            new StringBuilder("Ловать"),
            new StringBuilder("Каспля"),
            new StringBuilder("Вопь"),
            new StringBuilder("Ока"),
            new StringBuilder("1132- 1356 гг."),
            new StringBuilder("топью"),
            new StringBuilder("1157-1389 гг."),
            new StringBuilder("1141 год"),
            new StringBuilder("1180 год"),
            new StringBuilder("Ярослав Мудрый"),
            new StringBuilder("1207 год"),
            new StringBuilder("1250-1255 гг."),
            new StringBuilder("1252 год"),
            new StringBuilder("1308-1331 гг."),
            new StringBuilder("1389 год"),
            new StringBuilder("Всеволоду Ярославичу"),
            new StringBuilder("1155 год"),
            new StringBuilder("1172 год"),
            new StringBuilder("XIII"),
            new StringBuilder("1241-1248 гг."),
            new StringBuilder("1245 год"),
            new StringBuilder("1248 год"),
            new StringBuilder("Сборщик налогов"),
            new StringBuilder("1272 год"),
            new StringBuilder("1310 год"),
            new StringBuilder("Суздаль"),
            new StringBuilder("1326 году"),
            new StringBuilder("1352 году"),
            new StringBuilder("1330-1432 гг."),
            new StringBuilder("1241-1245 гг."),
            new StringBuilder("1216-1218 гг."),
            new StringBuilder("1250 год"),
            new StringBuilder("Иван III"),
            new StringBuilder("1264 год"),
            new StringBuilder("Его сыновья"),
            new StringBuilder("1408 год"),
            new StringBuilder("1349 год"),
            new StringBuilder("1360 год"),
            new StringBuilder("1356 год"),
            new StringBuilder("1370 год"),
            new StringBuilder("1373 год"),
            new StringBuilder("1370 год"),
            new StringBuilder("1376 год"),
            new StringBuilder("1390 год"),
            new StringBuilder("1400 год"),
            new StringBuilder("1388 год"),
            new StringBuilder("1383 год"),
            new StringBuilder("1414 год"),
            new StringBuilder("1455 год"),
            new StringBuilder("1288 год"),
            new StringBuilder("Андрей Александрович"),
            new StringBuilder("1340-1445 гг."),
            new StringBuilder("Александр Невский"),
            new StringBuilder("1452 год"),
            new StringBuilder("Московского"),
            new StringBuilder("1145-1491 гг."),
            new StringBuilder("Ярополк"),
            new StringBuilder("восстание"),
            new StringBuilder("Новгород"),
            new StringBuilder("Агора"),
            new StringBuilder("1480 год"),
            new StringBuilder("1482 год"),
            new StringBuilder("Иван III"),
            new StringBuilder("соль"),
            new StringBuilder("Любой желающий"),
            new StringBuilder("Равноправно"),
            new StringBuilder("На Торгу"),
            new StringBuilder("Агора"),
            new StringBuilder("1149 год"),
            new StringBuilder("Раздавали листовки"),
            new StringBuilder("1304 год"),
            new StringBuilder("1316 год"),
            new StringBuilder("1314 году"),
            new StringBuilder("1160 год"),
            new StringBuilder("1228 год"),
            new StringBuilder("Сура"),
            new StringBuilder("Пскове"),
            new StringBuilder("1141 год"),
            new StringBuilder("архиепископ"),
            new StringBuilder("Агора"),
            new StringBuilder("тысяцкие"),
            new StringBuilder("Тысяцкие"),
            new StringBuilder("Ремесленники"),
            new StringBuilder("Закупы"),
            new StringBuilder("Своеземцы"),
            new StringBuilder("Земцы"),
            new StringBuilder("1471 год"),
            new StringBuilder("1270-1545 гг."),
            new StringBuilder("Литовское"),
            new StringBuilder("XVI век"),
            new StringBuilder("1547 год"),
            new StringBuilder("Юрий Долгорукий"),
            new StringBuilder("1245 год"),
            new StringBuilder("1240 год"),
            new StringBuilder("1248 год"),
            new StringBuilder("1262 год"),
            new StringBuilder("1313 год"),
            new StringBuilder("1310 год"),
            new StringBuilder("Иван I"),
            new StringBuilder("1396 год"),
            new StringBuilder("1396 год"),
            new StringBuilder("1353 год"),
            new StringBuilder("1350 год"),
            new StringBuilder("Василий I"),
            new StringBuilder("1458 год"),
            new StringBuilder("1325 год"),
            new StringBuilder("1327 год"),
            new StringBuilder("1390 год"),
            new StringBuilder("11250 рублей"),
            new StringBuilder("1380 год"),
            new StringBuilder("1378 год"),
            new StringBuilder("р. Пахра"),
            new StringBuilder("1384 год"),
            new StringBuilder("1399 год"),
            new StringBuilder("1395 год"),
            new StringBuilder("заяц"),
            new StringBuilder("1313 год"),
            new StringBuilder("Москва"),
            new StringBuilder("Москва"),
            new StringBuilder("1458 год"),
            new StringBuilder("1472 год"),
            new StringBuilder("кража"),
            new StringBuilder("Конюший"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("Сокольничий"),
            new StringBuilder("Купец"),
            new StringBuilder("Боярин"),
            new StringBuilder("Сокольничий"),
            new StringBuilder("ясельничий"),
            new StringBuilder("Ловчий"),
            new StringBuilder("Домоуправлением"),
            new StringBuilder("Дьяк"),
            new StringBuilder("Ладья"),
            new StringBuilder("Ар"),
            new StringBuilder("торговые люди"),
            new StringBuilder("рабы"),
            new StringBuilder("Ключник"),
            new StringBuilder("Обжа"),
            new StringBuilder("Постельничий"),
            new StringBuilder("Пчеловод"),
            new StringBuilder("Тиун"),
            new StringBuilder("Тиун"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("Дружинник"),
            new StringBuilder("1240-1800 гг."),
            new StringBuilder("1390 год"),
            new StringBuilder("XV-XVI"),
            new StringBuilder("1810 год"),
            new StringBuilder("1827 год"),
            new StringBuilder("Англии"),
            new StringBuilder("Господарь"),
            new StringBuilder("1212 год"),
            new StringBuilder("1212 год"),
            new StringBuilder("1221 год"),
            new StringBuilder("1248-1249 гг."),
            new StringBuilder("1263 год"),
            new StringBuilder("1268 год"),
            new StringBuilder("1258 год"),
            new StringBuilder("1255 год"),
            new StringBuilder("Евгений III"),
            new StringBuilder("1269 год"),
            new StringBuilder("1271 год"),
            new StringBuilder("1263 год"),
            new StringBuilder("1275 год"),
            new StringBuilder("Сикхизмскую"),
            new StringBuilder("1321 год"),
            new StringBuilder("Евнутия"),
            new StringBuilder("1381 год"),
            new StringBuilder("1381 год"),
            new StringBuilder("1384 год"),
            new StringBuilder("1384 год"),
            new StringBuilder("1394 год"),
            new StringBuilder("1393 год"),
            new StringBuilder("1388 год"),
            new StringBuilder("1387 год"),
            new StringBuilder("1399 год"),
            new StringBuilder("1401 год"),
            new StringBuilder("1401 год"),
            new StringBuilder("Ядвиге"),
            new StringBuilder("1414 год"),
            new StringBuilder("Ягайла"),
            new StringBuilder("1410 год"),
            new StringBuilder("1405 год"),
            new StringBuilder("1420 год"),
            new StringBuilder("Победа Витовта"),
            new StringBuilder("1414 год"),
            new StringBuilder("1411 год"),
            new StringBuilder("1433 год"),
            new StringBuilder("1441 год"),
            new StringBuilder("1441 год"),
            new StringBuilder("Польша"),
            new StringBuilder("Таураге"),
            new StringBuilder("1400 год"),
            new StringBuilder("Казимир"),
            new StringBuilder("1440-1442 гг."),
            new StringBuilder("1446-1447 гг."),
            new StringBuilder("1443 год"),
            new StringBuilder("Вильнюсе"),
            new StringBuilder("1449 год"),
            new StringBuilder("1489 год"),
            new StringBuilder("Казимир"),
            new StringBuilder("Казимир"),
            new StringBuilder("Уния"),
            new StringBuilder("Посол"),
            new StringBuilder("1574 год"),
            new StringBuilder("XIX веке"),
            new StringBuilder("Славяне"),
            new StringBuilder("1610 год"),
            new StringBuilder("1601 год"),
            new StringBuilder("1601 год"),
            new StringBuilder("проклятье"),
            new StringBuilder("XV века"),
            new StringBuilder("золотой медалью"),
            new StringBuilder("1460 год"),
            new StringBuilder("XVI век"),
            new StringBuilder("11"),
            new StringBuilder("XIX века"),
            new StringBuilder("1369 год"),
            new StringBuilder("1544 год"),
            new StringBuilder("1600 год"),
            new StringBuilder("Увраж"),
            new StringBuilder("1521 год"),
            new StringBuilder("Франциск Скорина"),
            new StringBuilder("Балис Сруога"),
            new StringBuilder("Балис Сруога"),
            new StringBuilder("1531 год"),
            new StringBuilder("Иван Федоров"),
            new StringBuilder("1580 год"),
            new StringBuilder("Маруша Нефедьева"),
            new StringBuilder("1573 год"),
            new StringBuilder("Мартинас Мажвидас"),
            new StringBuilder("Балис Сруога"),
            new StringBuilder("1555 год"),
            new StringBuilder("XVIII век"),
            new StringBuilder("Йокубаса Моркунаса"),
            new StringBuilder("1616 год"),
            new StringBuilder("Пятрас Браженас"),
            new StringBuilder("1635 год"),
            new StringBuilder("14000 слов"),
            new StringBuilder("Кабуки"),
            new StringBuilder("Марине Шварновне"),
            new StringBuilder("Борис Константинович"),
            new StringBuilder("1132 г."),
            new StringBuilder("1134 г."),
            new StringBuilder("Каганов"),
            new StringBuilder("1130 г."),
            new StringBuilder("1157 г."),
            new StringBuilder("1149 г."),
            new StringBuilder("1142 г."),
            new StringBuilder("1145 г."),
            new StringBuilder("Владимир-на-Клязьме"),
            new StringBuilder("Киев"),
            new StringBuilder("Юрьев"),
            new StringBuilder("1160 г."),
            new StringBuilder("1147 г."),
            new StringBuilder("1163 г."),
            new StringBuilder("1163 г."),
            new StringBuilder("1160 г."),
            new StringBuilder("1157 г."),
            new StringBuilder("дочь бана Хорватии"),
            new StringBuilder("1"),
            new StringBuilder("Анна"),
            new StringBuilder("6"),
            new StringBuilder("2"),
            new StringBuilder("1152-1158 гг."),
            new StringBuilder("1156-1158 гг."),
            new StringBuilder("1149 г."),
            new StringBuilder("Ладогу"),
            new StringBuilder("1201-1258 гг."),
            new StringBuilder("1212-1215 гг."),
            new StringBuilder("1214-1228 и 1248-1252 гг."),
            new StringBuilder("1241 г."),
            new StringBuilder("1240-1255 гг."),
            new StringBuilder("1251-1253 гг."),
            new StringBuilder("Гавриил"),
            new StringBuilder("1228 г."),
            new StringBuilder("1230 г."),
            new StringBuilder("1225 г."),
            new StringBuilder("1220 г."),
            new StringBuilder("1239 г."),
            new StringBuilder("1240 г."),
            new StringBuilder("1232-1241 гг."),
            new StringBuilder("Юрьеве-Польском"),
            new StringBuilder("1251 г."),
            new StringBuilder("1259 г."),
            new StringBuilder("1260 г."),
            new StringBuilder("Мощи"),
            new StringBuilder("Анна"),
            new StringBuilder("5"),
            new StringBuilder("1251-1255 гг."),
            new StringBuilder("1256-1264 гг."),
            new StringBuilder("1257 г."),
            new StringBuilder("1256 г."),
            new StringBuilder("1255 г."),
            new StringBuilder("1256 г."),
            new StringBuilder("1273 г."),
            new StringBuilder("1276 г."),
            new StringBuilder("1271 г."),
            new StringBuilder("1268 г."),
            new StringBuilder("1260-1310 гг."),
            new StringBuilder("1287 г."),
            new StringBuilder("1309 г."),
            new StringBuilder("Бездетный"),
            new StringBuilder("1324 г."),
            new StringBuilder("1331-1337 гг."),
            new StringBuilder("1331 г."),
            new StringBuilder("1295-1355 гг."),
            new StringBuilder("1341-1353 гг."),
            new StringBuilder("1342-1345 гг."),
            new StringBuilder("1353 г."),
            new StringBuilder("Анна"),
            new StringBuilder("Ефимия"),
            new StringBuilder("1"),
            new StringBuilder("1323-1359 гг."),
            new StringBuilder("1356-1383 гг."),
            new StringBuilder("1370-1386 гг."),
            new StringBuilder("1370-1375 гг."),
            new StringBuilder("Завоеватель"),
            new StringBuilder("Хозяин"),
            new StringBuilder("Амфиктиония"),
            new StringBuilder("Конфедерация"),
            new StringBuilder("Симмахия"),
            new StringBuilder("Федерация"),
            new StringBuilder("Уния"),
            new StringBuilder("Протекторат"),
            new StringBuilder("Симмахия"),
            new StringBuilder("1419 г."),
            new StringBuilder("1821 г."),
            new StringBuilder("1421 г."),
            new StringBuilder("1418 г."),
            new StringBuilder("1413 г."),
            new StringBuilder("1816 г."),
            new StringBuilder("Небольшая деревня"),
            new StringBuilder("Делянка"),
            new StringBuilder("1413 г."),
            new StringBuilder("1814 г."),
            new StringBuilder("1484 г."),
            new StringBuilder("1800 г."),
            new StringBuilder("1504 г."),
            new StringBuilder("1811 г."),
            new StringBuilder("1520 г."),
            new StringBuilder("1801 г."),
            new StringBuilder("1525 г."),
            new StringBuilder("1788 г."),
            new StringBuilder("1515 г."),
            new StringBuilder("1796 г."),
            new StringBuilder("1513 г."),
            new StringBuilder("1818 г."),
            new StringBuilder("1577 г."),
            new StringBuilder("1801 г."),
            new StringBuilder("1566 г."),
            new StringBuilder("1818 г."),
            new StringBuilder("1580 г."),
            new StringBuilder("1804 г."),
            new StringBuilder("1566 г."),
            new StringBuilder("1818 г."),
            new StringBuilder("1580 г."),
            new StringBuilder("1783 г."),
            new StringBuilder("1620 г."),
            new StringBuilder("1800 г."),
            new StringBuilder("1815 г."),
            new StringBuilder("1800 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1815 г."),
            new StringBuilder("1808 г."),
            new StringBuilder("1802 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1821 г."),
            new StringBuilder("1432-1455 гг."),
            new StringBuilder("1430-1435 гг."),
            new StringBuilder("1389 г."),
            new StringBuilder("1447 г."),
            new StringBuilder("1441 г."),
            new StringBuilder("Василий Косой"),
            new StringBuilder("1433 г."),
            new StringBuilder("Ордынский хан"),
            new StringBuilder("Борис Тверской"),
            new StringBuilder("Софья Витовтовна"),
            new StringBuilder("1434 г."),
            new StringBuilder("1440-1450 гг."),
            new StringBuilder("1449 г."),
            new StringBuilder("1442 г."),
            new StringBuilder("река Череха"),
            new StringBuilder("1455 г."),
            new StringBuilder("Юрий Дмитриевич"),
            new StringBuilder("1444-1452 гг."),
            new StringBuilder("1445 г."),
            new StringBuilder("Нерехта"),
            new StringBuilder("1440/1441 г."),
            new StringBuilder("Евдокия Дмитриевна"),
            new StringBuilder("воевода Дятел"),
            new StringBuilder("Дмитрий Красный"),
            new StringBuilder("Деревушка"),
            new StringBuilder("1452 г."),
            new StringBuilder("Мамутяка"),
            new StringBuilder("1454 г."),
            new StringBuilder("1452 г."),
            new StringBuilder("1450 г."),
            new StringBuilder("1445 г."),
            new StringBuilder("1460 г."),
            new StringBuilder("Отпустил за выкуп"),
            new StringBuilder("37400 рублей"),
            new StringBuilder("1446 г."),
            new StringBuilder("1464 г."),
            new StringBuilder("Битва у Вильны"),
            new StringBuilder("1460 г."),
            new StringBuilder("1456 г."),
            new StringBuilder("Продал татарам")
    };

    public Question4() {}
}