package studio.rashka.Test;

public class Question1 {

    public StringBuilder[] V1 = new StringBuilder[]{
            new StringBuilder("Волга"),
            new StringBuilder("Каспля"),
            new StringBuilder("Сож"),
            new StringBuilder("Лелевка"),
            new StringBuilder("Каспля"),
            new StringBuilder("1120-1380 гг."),
            new StringBuilder("хутором"),
            new StringBuilder("1138-1351 гг."),
            new StringBuilder("1125 год"),
            new StringBuilder("1151 год"),
            new StringBuilder("Юрий Долгорукий"),
            new StringBuilder("1148 год"),
            new StringBuilder("1237-1238 гг."),
            new StringBuilder("1240 год"),
            new StringBuilder("1304-1315 гг."),
            new StringBuilder("1371 год"),
            new StringBuilder("Василию Дмитриевичу"),
            new StringBuilder("1141 год"),
            new StringBuilder("1159 год"),
            new StringBuilder("X"),
            new StringBuilder("1226-1231 гг."),
            new StringBuilder("1232 год"),
            new StringBuilder("1237 год"),
            new StringBuilder("Воин"),
            new StringBuilder("1262 году"),
            new StringBuilder("1292 год"),
            new StringBuilder("Москва"),
            new StringBuilder("1288 году"),
            new StringBuilder("1341 году"),
            new StringBuilder("1322-1420 гг."),
            new StringBuilder("1216-1218 гг."),
            new StringBuilder("1212-1216 гг."),
            new StringBuilder("1238 год"),
            new StringBuilder("Александр Невский"),
            new StringBuilder("1255 год"),
            new StringBuilder("Вече"),
            new StringBuilder("1392 год"),
            new StringBuilder("1328 год"),
            new StringBuilder("1330 год"),
            new StringBuilder("1341 год"),
            new StringBuilder("1359 год"),
            new StringBuilder("1358 год"),
            new StringBuilder("1348 год"),
            new StringBuilder("1362 год"),
            new StringBuilder("1377 год"),
            new StringBuilder("1370 год"),
            new StringBuilder("1371 год"),
            new StringBuilder("1362 год"),
            new StringBuilder("1392 год"),
            new StringBuilder("1440 год"),
            new StringBuilder("1271 год"),
            new StringBuilder("Дмитрий Михайлович"),
            new StringBuilder("1387-1448 гг."),
            new StringBuilder("Василий Кирдяп"),
            new StringBuilder("1433 год"),
            new StringBuilder("Тверского"),
            new StringBuilder("1136-1478 гг."),
            new StringBuilder("Олег"),
            new StringBuilder("набеги на города"),
            new StringBuilder("Вологда"),
            new StringBuilder("Вече"),
            new StringBuilder("1467 год"),
            new StringBuilder("1466 год"),
            new StringBuilder("Биргер"),
            new StringBuilder("вечевой колокол"),
            new StringBuilder("Крестьяне"),
            new StringBuilder("От назначения в вече"),
            new StringBuilder("Руки вверх"),
            new StringBuilder("Вече"),
            new StringBuilder("1132 год"),
            new StringBuilder("Был день вече"),
            new StringBuilder("1288 год"),
            new StringBuilder("1304 год"),
            new StringBuilder("1300 году"),
            new StringBuilder("1148 год"),
            new StringBuilder("1203 год"),
            new StringBuilder("Посадник"),
            new StringBuilder("Москве"),
            new StringBuilder("1128 год"),
            new StringBuilder("тысяцкий"),
            new StringBuilder("Тысяцкий"),
            new StringBuilder("вече"),
            new StringBuilder("Купцы"),
            new StringBuilder("Купцы"),
            new StringBuilder("Своеземцы"),
            new StringBuilder("Паломники"),
            new StringBuilder("Кочетники"),
            new StringBuilder("1462 год"),
            new StringBuilder("1263-1547 гг."),
            new StringBuilder("Смоленское"),
            new StringBuilder("XIII век"),
            new StringBuilder("1517 год"),
            new StringBuilder("Даниил Александрович"),
            new StringBuilder("1235 год"),
            new StringBuilder("1228 год"),
            new StringBuilder("1238 год"),
            new StringBuilder("1249 год"),
            new StringBuilder("1297 год"),
            new StringBuilder("1288 год"),
            new StringBuilder("Владимир Мономах"),
            new StringBuilder("1385 год"),
            new StringBuilder("1384 год"),
            new StringBuilder("1339 год"),
            new StringBuilder("1331 год"),
            new StringBuilder("Ольгерд Гедиминович"),
            new StringBuilder("1445 год"),
            new StringBuilder("1300 год"),
            new StringBuilder("1300 год"),
            new StringBuilder("1371 год"),
            new StringBuilder("9300 рублей"),
            new StringBuilder("1367 год"),
            new StringBuilder("1366 год"),
            new StringBuilder("р. Воже"),
            new StringBuilder("1377 год"),
            new StringBuilder("1380 год"),
            new StringBuilder("1380 год"),
            new StringBuilder("народ"),
            new StringBuilder("1295 год"),
            new StringBuilder("Смоленск"),
            new StringBuilder("Смоленск"),
            new StringBuilder("1439 год"),
            new StringBuilder("1457 год"),
            new StringBuilder("убийство"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("Сокольничий"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("Окольничий"),
            new StringBuilder("дружинник"),
            new StringBuilder("Воевода"),
            new StringBuilder("Воровали"),
            new StringBuilder("Казначей"),
            new StringBuilder("Крамола"),
            new StringBuilder("Копна"),
            new StringBuilder("рабы"),
            new StringBuilder("торговые люди"),
            new StringBuilder("Дьяк"),
            new StringBuilder("Дружинник"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("Чашник"),
            new StringBuilder("Чашник"),
            new StringBuilder("Чашник"),
            new StringBuilder("Рында"),
            new StringBuilder("Оружничий"),
            new StringBuilder("1234-1799 гг."),
            new StringBuilder("1378 год"),
            new StringBuilder("XV"),
            new StringBuilder("1795 год"),
            new StringBuilder("1810 год"),
            new StringBuilder("Венгрии"),
            new StringBuilder("Верховный"),
            new StringBuilder("1190 год"),
            new StringBuilder("1194 год"),
            new StringBuilder("1207 год"),
            new StringBuilder("1248 год"),
            new StringBuilder("1251 год"),
            new StringBuilder("1255 год"),
            new StringBuilder("1248 год"),
            new StringBuilder("1241 год"),
            new StringBuilder("Александр IV"),
            new StringBuilder("1257 год"),
            new StringBuilder("1248 год"),
            new StringBuilder("1247 год"),
            new StringBuilder("1265 год"),
            new StringBuilder("Католическую"),
            new StringBuilder("1301 год"),
            new StringBuilder("Кориата"),
            new StringBuilder("1368 и 1370 гг."),
            new StringBuilder("1368 год"),
            new StringBuilder("1370 год"),
            new StringBuilder("1370 год"),
            new StringBuilder("1384 год"),
            new StringBuilder("1381 год"),
            new StringBuilder("1379 год"),
            new StringBuilder("1377 год"),
            new StringBuilder("1390 год"),
            new StringBuilder("1389 год"),
            new StringBuilder("1387 год"),
            new StringBuilder("Наримунту"),
            new StringBuilder("1399 год"),
            new StringBuilder("Монвида"),
            new StringBuilder("1388 год"),
            new StringBuilder("1388 год"),
            new StringBuilder("1406 год"),
            new StringBuilder("Расходятся"),
            new StringBuilder("1400 год"),
            new StringBuilder("1398 год"),
            new StringBuilder("1411 год"),
            new StringBuilder("1424 год"),
            new StringBuilder("1410 год"),
            new StringBuilder("Рим"),
            new StringBuilder("Тракай"),
            new StringBuilder("1428 год"),
            new StringBuilder("Свидригайло"),
            new StringBuilder("1430-1432 гг."),
            new StringBuilder("1440-1442 гг."),
            new StringBuilder("1437 год"),
            new StringBuilder("Бутинге"),
            new StringBuilder("1433 год"),
            new StringBuilder("1480 год"),
            new StringBuilder("Василий II"),
            new StringBuilder("Сигизмунд"),
            new StringBuilder("Симмахия"),
            new StringBuilder("Князь"),
            new StringBuilder("1566 год"),
            new StringBuilder("XVI веке"),
            new StringBuilder("Монголы"),
            new StringBuilder("1596 год"),
            new StringBuilder("1591 год"),
            new StringBuilder("1589 год"),
            new StringBuilder("казнь"),
            new StringBuilder("XIV-XV веках"),
            new StringBuilder("ничем"),
            new StringBuilder("1448 год"),
            new StringBuilder("X век"),
            new StringBuilder("3-5"),
            new StringBuilder("XV-XVI веках"),
            new StringBuilder("1357 год"),
            new StringBuilder("1537 год"),
            new StringBuilder("1579 год"),
            new StringBuilder("Библия"),
            new StringBuilder("1507 год"),
            new StringBuilder("Балис Сруога"),
            new StringBuilder("Франциск Скорина"),
            new StringBuilder("Пятрас Браженас"),
            new StringBuilder("1506 год"),
            new StringBuilder("Маруша Нефедьева"),
            new StringBuilder("1568 год"),
            new StringBuilder("Петр Мстиславец"),
            new StringBuilder("1562 год"),
            new StringBuilder("Балис Сруога"),
            new StringBuilder("Мартинас Мажвидас"),
            new StringBuilder("1543 год"),
            new StringBuilder("XIV век"),
            new StringBuilder("Владас Дубас"),
            new StringBuilder("1600 год"),
            new StringBuilder("Йокубаса Моркунаса"),
            new StringBuilder("1613 год"),
            new StringBuilder("11000 слов"),
            new StringBuilder("Вертеп"),
            new StringBuilder("Михаилу Ярославичу"),
            new StringBuilder("Михаил Андреевич"),
            new StringBuilder("1121 г."),
            new StringBuilder("1120 г."),
            new StringBuilder("Византию"),
            new StringBuilder("1118 г."),
            new StringBuilder("1145 г."),
            new StringBuilder("1134 г."),
            new StringBuilder("1129 г."),
            new StringBuilder("1127 г."),
            new StringBuilder("Ладогу"),
            new StringBuilder("Кидекша"),
            new StringBuilder("Звенигород"),
            new StringBuilder("1148 г."),
            new StringBuilder("1132 г."),
            new StringBuilder("1146 г."),
            new StringBuilder("1146 г."),
            new StringBuilder("1139 г."),
            new StringBuilder("1136 г."),
            new StringBuilder("дочь хана Аепы Осеневича"),
            new StringBuilder("12"),
            new StringBuilder("Александра"),
            new StringBuilder("1"),
            new StringBuilder("14"),
            new StringBuilder("1142-1148 гг."),
            new StringBuilder("1142-1148 гг."),
            new StringBuilder("1132 г."),
            new StringBuilder("Византию"),
            new StringBuilder("1192-1247 гг."),
            new StringBuilder("1198-1203 гг."),
            new StringBuilder("1212-1221 гг."),
            new StringBuilder("1228-1230 гг."),
            new StringBuilder("1236-1244 гг."),
            new StringBuilder("1238-1248 гг."),
            new StringBuilder("Инг"),
            new StringBuilder("1212 г."),
            new StringBuilder("1202 г."),
            new StringBuilder("1210 г."),
            new StringBuilder("1206 г."),
            new StringBuilder("1222 г."),
            new StringBuilder("1220 г."),
            new StringBuilder("1220-1224 гг."),
            new StringBuilder("Суздале"),
            new StringBuilder("1238 г."),
            new StringBuilder("1243 г."),
            new StringBuilder("1239 г."),
            new StringBuilder("Мослак"),
            new StringBuilder("Евдокия"),
            new StringBuilder("Бездетный"),
            new StringBuilder("1240-1243 гг."),
            new StringBuilder("1248-1253 гг."),
            new StringBuilder("1242 г."),
            new StringBuilder("1242 г."),
            new StringBuilder("1240 г."),
            new StringBuilder("1242 г."),
            new StringBuilder("1264-1279 гг."),
            new StringBuilder("1261 г."),
            new StringBuilder("1260 г."),
            new StringBuilder("1257 г."),
            new StringBuilder("1250-1305 гг."),
            new StringBuilder("1277-1288 гг."),
            new StringBuilder("1289 г."),
            new StringBuilder("8"),
            new StringBuilder("1309-1331 гг."),
            new StringBuilder("1326-1330 гг."),
            new StringBuilder("1309 г."),
            new StringBuilder("1289-1347 гг."),
            new StringBuilder("1332-1355 гг."),
            new StringBuilder("1337 г."),
            new StringBuilder("1340 г."),
            new StringBuilder("Ефимия"),
            new StringBuilder("Елена"),
            new StringBuilder("8"),
            new StringBuilder("1311-1373 гг."),
            new StringBuilder("1356-1347 гг."),
            new StringBuilder("1365-1383 гг."),
            new StringBuilder("1357-1354 гг."),
            new StringBuilder("Царь"),
            new StringBuilder("Крестьянин"),
            new StringBuilder("Уния"),
            new StringBuilder("Симмахия"),
            new StringBuilder("Амфиктиония"),
            new StringBuilder("Уния"),
            new StringBuilder("Династия"),
            new StringBuilder("Симмахия"),
            new StringBuilder("Уния"),
            new StringBuilder("1387 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1396 г."),
            new StringBuilder("1388 г."),
            new StringBuilder("1388 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("Город"),
            new StringBuilder("Усадьба"),
            new StringBuilder("1379 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1467 г."),
            new StringBuilder("1782 г."),
            new StringBuilder("1488 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1501 г."),
            new StringBuilder("1787 г."),
            new StringBuilder("1508 г."),
            new StringBuilder("1772 г."),
            new StringBuilder("1502 г."),
            new StringBuilder("1781 г."),
            new StringBuilder("1499 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1560 г."),
            new StringBuilder("1783 г."),
            new StringBuilder("1533 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1561 г."),
            new StringBuilder("1782 г."),
            new StringBuilder("1499 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1560 г."),
            new StringBuilder("1760 г."),
            new StringBuilder("1589 г."),
            new StringBuilder("1772 г."),
            new StringBuilder("1787 г."),
            new StringBuilder("1781 г."),
            new StringBuilder("1777 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1788 г."),
            new StringBuilder("1788 г."),
            new StringBuilder("1777 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1422-1437 гг."),
            new StringBuilder("1411-1414 гг."),
            new StringBuilder("1371 г."),
            new StringBuilder("1425 г."),
            new StringBuilder("1425 г."),
            new StringBuilder("Дмитрий Шемяка"),
            new StringBuilder("1401 г."),
            new StringBuilder("Софья Витовтовна"),
            new StringBuilder("Василий Косой"),
            new StringBuilder("Василий Косой"),
            new StringBuilder("1402 г."),
            new StringBuilder("1434-1436 гг."),
            new StringBuilder("1431 г."),
            new StringBuilder("1428 г."),
            new StringBuilder("Нерехта"),
            new StringBuilder("1436 г."),
            new StringBuilder("Василий Косой"),
            new StringBuilder("1420-1435 гг."),
            new StringBuilder("1436 г."),
            new StringBuilder("Суздаль"),
            new StringBuilder("1433 г."),
            new StringBuilder("Софья Витовтовна"),
            new StringBuilder("Василий Косой"),
            new StringBuilder("дворянин Жадовский"),
            new StringBuilder("Уголь"),
            new StringBuilder("1437 г."),
            new StringBuilder("Иван Можайский"),
            new StringBuilder("1439 г."),
            new StringBuilder("1440 г."),
            new StringBuilder("1437 г."),
            new StringBuilder("1432 г."),
            new StringBuilder("1446 г."),
            new StringBuilder("Повесил"),
            new StringBuilder("12500 рублей"),
            new StringBuilder("1432 г."),
            new StringBuilder("1449 г."),
            new StringBuilder("Они не встречались"),
            new StringBuilder("1440 г."),
            new StringBuilder("1441 г."),
            new StringBuilder("Навязал Яжелбицкий договор")
    };

    public Question1() {}
}