package studio.rashka.Test;

public class Question3 {

    public StringBuilder[] V3 = new StringBuilder[]{
            new StringBuilder("Ипуть"),
            new StringBuilder("Торопа"),
            new StringBuilder("Днепр"),
            new StringBuilder("Выдра"),
            new StringBuilder("Волга"),
            new StringBuilder("1131-1373 гг."),
            new StringBuilder("уделом"),
            new StringBuilder("1157-1379 гг."),
            new StringBuilder("1138 год"),
            new StringBuilder("1162 год"),
            new StringBuilder("Андрей Боголюбский"),
            new StringBuilder("1189 год"),
            new StringBuilder("1243-1248 гг."),
            new StringBuilder("1248 год"),
            new StringBuilder("1304-1328 гг."),
            new StringBuilder("1383 год"),
            new StringBuilder("Юрию Владимировичу"),
            new StringBuilder("1149 год"),
            new StringBuilder("1169 год"),
            new StringBuilder("XII"),
            new StringBuilder("1238-1242 гг."),
            new StringBuilder("1241 год"),
            new StringBuilder("1243 год"),
            new StringBuilder("Посол"),
            new StringBuilder("1268 год"),
            new StringBuilder("1304 год"),
            new StringBuilder("Владимир"),
            new StringBuilder("1310 году"),
            new StringBuilder("1349 году"),
            new StringBuilder("1330-1429 гг."),
            new StringBuilder("1216-1218 и 1238-1341"),
            new StringBuilder("1215-1217 гг."),
            new StringBuilder("1245 год"),
            new StringBuilder("Ярополк"),
            new StringBuilder("1260 год"),
            new StringBuilder("Монголы"),
            new StringBuilder("1400 год"),
            new StringBuilder("1345 год"),
            new StringBuilder("1350 год"),
            new StringBuilder("1352 год"),
            new StringBuilder("1366 год"),
            new StringBuilder("1368 год"),
            new StringBuilder("1366 год"),
            new StringBuilder("1371 год"),
            new StringBuilder("1384 год"),
            new StringBuilder("1390 год"),
            new StringBuilder("1382 год"),
            new StringBuilder("1374 год"),
            new StringBuilder("1408 год"),
            new StringBuilder("1450 год"),
            new StringBuilder("1282 год"),
            new StringBuilder("Александр Невский"),
            new StringBuilder("1389-1452 гг."),
            new StringBuilder("Дмитрий Шимяков"),
            new StringBuilder("1448 год"),
            new StringBuilder("Литовского"),
            new StringBuilder("1140-1483 гг."),
            new StringBuilder("Ярослав"),
            new StringBuilder("новое правление"),
            new StringBuilder("Торжок"),
            new StringBuilder("Сходбище"),
            new StringBuilder("1476 год"),
            new StringBuilder("1478 год"),
            new StringBuilder("Всеволод"),
            new StringBuilder("золото"),
            new StringBuilder("Избранные народом"),
            new StringBuilder("От социального статуса"),
            new StringBuilder("Да будет так"),
            new StringBuilder("Сходбище"),
            new StringBuilder("1141 год"),
            new StringBuilder("Звонили в колокола"),
            new StringBuilder("1297 год"),
            new StringBuilder("1312 год"),
            new StringBuilder("1310 году"),
            new StringBuilder("1156 год"),
            new StringBuilder("1220 год"),
            new StringBuilder("Мирза"),
            new StringBuilder("Смоленске"),
            new StringBuilder("1136 год"),
            new StringBuilder("посадник"),
            new StringBuilder("Мирза"),
            new StringBuilder("сотские старосты"),
            new StringBuilder("Бояре"),
            new StringBuilder("Рабы"),
            new StringBuilder("Изорники"),
            new StringBuilder("Закупы"),
            new StringBuilder("Смерды"),
            new StringBuilder("1468 год"),
            new StringBuilder("1266-1551 гг."),
            new StringBuilder("Новгородское"),
            new StringBuilder("XV век"),
            new StringBuilder("1537 год"),
            new StringBuilder("Юрий Всеволодович"),
            new StringBuilder("1241 год"),
            new StringBuilder("1236 год"),
            new StringBuilder("1245 год"),
            new StringBuilder("1258 год"),
            new StringBuilder("1308 год"),
            new StringBuilder("1303 год"),
            new StringBuilder("Иван II"),
            new StringBuilder("1394 год"),
            new StringBuilder("1391 год"),
            new StringBuilder("1349 год"),
            new StringBuilder("1344 год"),
            new StringBuilder("Иван I Калита"),
            new StringBuilder("1453 год"),
            new StringBuilder("1317 год"),
            new StringBuilder("1320 год"),
            new StringBuilder("1381 год"),
            new StringBuilder("11000 рублей"),
            new StringBuilder("1374 год"),
            new StringBuilder("1373 год"),
            new StringBuilder("р. Ока"),
            new StringBuilder("1388 год"),
            new StringBuilder("1391 год"),
            new StringBuilder("1390 год"),
            new StringBuilder("олень"),
            new StringBuilder("1308 год"),
            new StringBuilder("Владимир"),
            new StringBuilder("Владимир"),
            new StringBuilder("1449 год"),
            new StringBuilder("1467 год"),
            new StringBuilder("смута"),
            new StringBuilder("Сокольничий"),
            new StringBuilder("Ловчий"),
            new StringBuilder("Конюший"),
            new StringBuilder("Думный дворянин"),
            new StringBuilder("Дружинник"),
            new StringBuilder("Ловчий"),
            new StringBuilder("окольничий"),
            new StringBuilder("Думный дьяк"),
            new StringBuilder("Делали ключи"),
            new StringBuilder("Ловчий"),
            new StringBuilder("Улус"),
            new StringBuilder("Обжа"),
            new StringBuilder("перевозчики"),
            new StringBuilder("дружинники"),
            new StringBuilder("Ловчий"),
            new StringBuilder("Рында"),
            new StringBuilder("Рында"),
            new StringBuilder("Тиун"),
            new StringBuilder("Дьяк"),
            new StringBuilder("Кравчий"),
            new StringBuilder("Тиун"),
            new StringBuilder("Рында"),
            new StringBuilder("1238-1788 гг."),
            new StringBuilder("1385 год"),
            new StringBuilder("XIV-XV"),
            new StringBuilder("1801 год"),
            new StringBuilder("1821 год"),
            new StringBuilder("России"),
            new StringBuilder("Князь"),
            new StringBuilder("1198 год"),
            new StringBuilder("1205 год"),
            new StringBuilder("1216 год"),
            new StringBuilder("1247-1251 гг."),
            new StringBuilder("1259 год"),
            new StringBuilder("1263 год"),
            new StringBuilder("1255 год"),
            new StringBuilder("1252 год"),
            new StringBuilder("Адриан IV"),
            new StringBuilder("1266 год"),
            new StringBuilder("1260 год"),
            new StringBuilder("1257 год"),
            new StringBuilder("1271 год"),
            new StringBuilder("Исламскую"),
            new StringBuilder("1317 год"),
            new StringBuilder("Монвида"),
            new StringBuilder("1376 год"),
            new StringBuilder("1376 год"),
            new StringBuilder("1380 год"),
            new StringBuilder("1380 год"),
            new StringBuilder("1392 год"),
            new StringBuilder("1389 год"),
            new StringBuilder("1385 год"),
            new StringBuilder("1384 год"),
            new StringBuilder("1396 год"),
            new StringBuilder("1395 год"),
            new StringBuilder("1395 год"),
            new StringBuilder("Василию I"),
            new StringBuilder("1408 год"),
            new StringBuilder("Наримунта"),
            new StringBuilder("1401 год"),
            new StringBuilder("1397 год"),
            new StringBuilder("1414 год"),
            new StringBuilder("Победа Василия I"),
            new StringBuilder("1410 год"),
            new StringBuilder("1407 год"),
            new StringBuilder("1425 год"),
            new StringBuilder("1431 год"),
            new StringBuilder("1430 год"),
            new StringBuilder("Италия"),
            new StringBuilder("Утена"),
            new StringBuilder("1436 год"),
            new StringBuilder("Сигизмунда"),
            new StringBuilder("1437-1440 гг."),
            new StringBuilder("1445-1448 гг."),
            new StringBuilder("1442 год"),
            new StringBuilder("Троках"),
            new StringBuilder("1444 год"),
            new StringBuilder("1484 год"),
            new StringBuilder("Сигизмунд"),
            new StringBuilder("Иван III"),
            new StringBuilder("Коалиция"),
            new StringBuilder("Архиепископ"),
            new StringBuilder("1573 год"),
            new StringBuilder("XIV-XVI веках"),
            new StringBuilder("Пруссы"),
            new StringBuilder("1606 год"),
            new StringBuilder("1598 год"),
            new StringBuilder("1596 год"),
            new StringBuilder("посвящение"),
            new StringBuilder("XIV века"),
            new StringBuilder("серебряной медалью"),
            new StringBuilder("1454 год"),
            new StringBuilder("XV век"),
            new StringBuilder("9"),
            new StringBuilder("XVII-XVIII веках"),
            new StringBuilder("1364 год"),
            new StringBuilder("1541 год"),
            new StringBuilder("1591 год"),
            new StringBuilder("Пафлет"),
            new StringBuilder("1517 год"),
            new StringBuilder("Пятрас Браженас"),
            new StringBuilder("Владас Дубас"),
            new StringBuilder("Владас Дубас"),
            new StringBuilder("1526 год"),
            new StringBuilder("Петр Мстиславец"),
            new StringBuilder("1574 год"),
            new StringBuilder("Максим Смотрицкий"),
            new StringBuilder("1570 год"),
            new StringBuilder("Пятрас Браженас"),
            new StringBuilder("Владас Дубас"),
            new StringBuilder("1551 год"),
            new StringBuilder("XVI век"),
            new StringBuilder("Мартинас Мажвидас"),
            new StringBuilder("1609 год"),
            new StringBuilder("Мартинас Мажвидас"),
            new StringBuilder("1629 год"),
            new StringBuilder("13000 слов"),
            new StringBuilder("Эстрада"),
            new StringBuilder("Всеволоду Юрьевичу"),
            new StringBuilder("Юрий Долгорукий"),
            new StringBuilder("1129 г."),
            new StringBuilder("1129 г."),
            new StringBuilder("Половцев"),
            new StringBuilder("1125 г."),
            new StringBuilder("1153 г."),
            new StringBuilder("1142 г."),
            new StringBuilder("1139 г."),
            new StringBuilder("1139 г."),
            new StringBuilder("Москву"),
            new StringBuilder("Москва"),
            new StringBuilder("Дубна"),
            new StringBuilder("1154 г."),
            new StringBuilder("1142 г."),
            new StringBuilder("1158 г."),
            new StringBuilder("1158 г."),
            new StringBuilder("1155 г."),
            new StringBuilder("1149 г."),
            new StringBuilder("дочь Конрада III"),
            new StringBuilder("4"),
            new StringBuilder("Ольга"),
            new StringBuilder("4"),
            new StringBuilder("5"),
            new StringBuilder("1150-1156 гг."),
            new StringBuilder("1155-1161 гг."),
            new StringBuilder("1142 г."),
            new StringBuilder("Москву"),
            new StringBuilder("1200-1249 гг."),
            new StringBuilder("1200-1205 и 1208-1210 гг."),
            new StringBuilder("1241-1263 гг."),
            new StringBuilder("1232-1238 гг."),
            new StringBuilder("1240-1250 гг."),
            new StringBuilder("1246-1248 гг."),
            new StringBuilder("Казимир"),
            new StringBuilder("1221 г."),
            new StringBuilder("1221 г."),
            new StringBuilder("1220 г."),
            new StringBuilder("1212 г."),
            new StringBuilder("1234 г."),
            new StringBuilder("1232 г."),
            new StringBuilder("1230-1234 гг."),
            new StringBuilder("Москве"),
            new StringBuilder("1248 г."),
            new StringBuilder("1252 г."),
            new StringBuilder("1250 г."),
            new StringBuilder("Прах"),
            new StringBuilder("София"),
            new StringBuilder("3"),
            new StringBuilder("1248-1252 гг."),
            new StringBuilder("1254-1261 гг."),
            new StringBuilder("1253 г."),
            new StringBuilder("1251 г."),
            new StringBuilder("1250 г."),
            new StringBuilder("1252 г."),
            new StringBuilder("1268-1284 гг."),
            new StringBuilder("1271 г."),
            new StringBuilder("1268 г."),
            new StringBuilder("1265 г."),
            new StringBuilder("1254-1289 гг."),
            new StringBuilder("1283 г."),
            new StringBuilder("1305 г."),
            new StringBuilder("2"),
            new StringBuilder("1319 г."),
            new StringBuilder("1328-1327 гг."),
            new StringBuilder("1327 г."),
            new StringBuilder("1293-1361 гг."),
            new StringBuilder("1337-1350 гг."),
            new StringBuilder("1346 г."),
            new StringBuilder("1350 г."),
            new StringBuilder("София"),
            new StringBuilder("Агафья"),
            new StringBuilder("3"),
            new StringBuilder("1322-1383 гг."),
            new StringBuilder("1356-1372 гг."),
            new StringBuilder("1370-1380 гг."),
            new StringBuilder("1362-1369 гг."),
            new StringBuilder("Господарь"),
            new StringBuilder("Боярин"),
            new StringBuilder("Альянс"),
            new StringBuilder("Уния"),
            new StringBuilder("Церковная уния"),
            new StringBuilder("Протекторат"),
            new StringBuilder("Протекторат"),
            new StringBuilder("Уния"),
            new StringBuilder("Вассалитет"),
            new StringBuilder("1410 г."),
            new StringBuilder("1818 г."),
            new StringBuilder("1414 г."),
            new StringBuilder("1413 г."),
            new StringBuilder("1404 г."),
            new StringBuilder("1809 г."),
            new StringBuilder("Дома феодалов"),
            new StringBuilder("Дым"),
            new StringBuilder("1399 г."),
            new StringBuilder("1808 г."),
            new StringBuilder("1477 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1498 г."),
            new StringBuilder("1803 г."),
            new StringBuilder("1512 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1519 г."),
            new StringBuilder("1782 г."),
            new StringBuilder("1512 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1510 г."),
            new StringBuilder("1806 г."),
            new StringBuilder("1571 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1559 г."),
            new StringBuilder("1809 г."),
            new StringBuilder("1572 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1547 г."),
            new StringBuilder("1809 г."),
            new StringBuilder("1571 г."),
            new StringBuilder("1772 г."),
            new StringBuilder("1608 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1804 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1788 г."),
            new StringBuilder("1808 г."),
            new StringBuilder("1802 г."),
            new StringBuilder("1795 г."),
            new StringBuilder("1789 г."),
            new StringBuilder("1810 г."),
            new StringBuilder("1428-1440 гг."),
            new StringBuilder("1425-1433 гг."),
            new StringBuilder("1382 г."),
            new StringBuilder("1439 г."),
            new StringBuilder("1438 г."),
            new StringBuilder("Василий Темный"),
            new StringBuilder("1426 г."),
            new StringBuilder("Дмитрий Шемяка"),
            new StringBuilder("Дмитрий Шемяка"),
            new StringBuilder("Василий Темный"),
            new StringBuilder("1426 г."),
            new StringBuilder("1438-1445 гг."),
            new StringBuilder("1442 г."),
            new StringBuilder("1436 г."),
            new StringBuilder("Вологда"),
            new StringBuilder("1449 г."),
            new StringBuilder("Дмитрий Красный"),
            new StringBuilder("1436-1453 гг."),
            new StringBuilder("1442 г."),
            new StringBuilder("Киев"),
            new StringBuilder("1439 г."),
            new StringBuilder("Василий Косой"),
            new StringBuilder("дворянин Жадовский"),
            new StringBuilder("Василий Косой"),
            new StringBuilder("Город"),
            new StringBuilder("1445 г."),
            new StringBuilder("Василий Косой"),
            new StringBuilder("1448 г."),
            new StringBuilder("1448 г."),
            new StringBuilder("1445 г."),
            new StringBuilder("1441 г."),
            new StringBuilder("1457 г."),
            new StringBuilder("Казнил"),
            new StringBuilder("25000 рублей"),
            new StringBuilder("1441 г."),
            new StringBuilder("1459 г."),
            new StringBuilder("Битва у Москвы"),
            new StringBuilder("1452 г."),
            new StringBuilder("1450 г."),
            new StringBuilder("Сжег")
    };

    public Question3() {}
}