package studio.rashka.Test;

public class Question2 {

    public StringBuilder[] V2 = new StringBuilder[]{
            new StringBuilder("Десна"),
            new StringBuilder("Песочная"),
            new StringBuilder("Двина"),
            new StringBuilder("Ольша"),
            new StringBuilder("Вазува"),
            new StringBuilder("1127-1387 гг."),
            new StringBuilder("недрой"),
            new StringBuilder("1149-1348 гг."),
            new StringBuilder("1131 год"),
            new StringBuilder("1157 год"),
            new StringBuilder("Владимир Мономах"),
            new StringBuilder("1167 год"),
            new StringBuilder("1241-1245 гг."),
            new StringBuilder("1243 год"),
            new StringBuilder("1304-1325 гг."),
            new StringBuilder("1379 год"),
            new StringBuilder("Александру Васильевичу"),
            new StringBuilder("1146 год"),
            new StringBuilder("1164 год"),
            new StringBuilder("XI"),
            new StringBuilder("1226-1240 гг."),
            new StringBuilder("1238 год"),
            new StringBuilder("1240 год"),
            new StringBuilder("Купец"),
            new StringBuilder("1265 год"),
            new StringBuilder("1299 год"),
            new StringBuilder("Киев"),
            new StringBuilder("1296 году"),
            new StringBuilder("1345 году"),
            new StringBuilder("1328-1424 гг."),
            new StringBuilder("1238-1341 гг."),
            new StringBuilder("1214-1216 гг."),
            new StringBuilder("1241 год"),
            new StringBuilder("Святослав"),
            new StringBuilder("1257 год"),
            new StringBuilder("Александр Невский"),
            new StringBuilder("1397 год"),
            new StringBuilder("1341 год"),
            new StringBuilder("1340 год"),
            new StringBuilder("1349 год"),
            new StringBuilder("1362 год"),
            new StringBuilder("1362 год"),
            new StringBuilder("1357 год"),
            new StringBuilder("1367 год"),
            new StringBuilder("1380 год"),
            new StringBuilder("1380 год"),
            new StringBuilder("1379 год"),
            new StringBuilder("1368 год"),
            new StringBuilder("1399 год"),
            new StringBuilder("1445 год"),
            new StringBuilder("1276 год"),
            new StringBuilder("Михаил Ярославич"),
            new StringBuilder("1388-1450 гг."),
            new StringBuilder("Юрий Васильевич"),
            new StringBuilder("1440 год"),
            new StringBuilder("Ростовского"),
            new StringBuilder("1138-1480 гг."),
            new StringBuilder("Всеволод"),
            new StringBuilder("производство лодок"),
            new StringBuilder("Волок"),
            new StringBuilder("Скопище"),
            new StringBuilder("1471 год"),
            new StringBuilder("1472 год"),
            new StringBuilder("Олег"),
            new StringBuilder("пушнину"),
            new StringBuilder("Главы поселений"),
            new StringBuilder("От привилегий сверху"),
            new StringBuilder("Так оно и быть"),
            new StringBuilder("Скопище"),
            new StringBuilder("1136 год"),
            new StringBuilder("Был посыльный"),
            new StringBuilder("1292 год"),
            new StringBuilder("1308 год"),
            new StringBuilder("1305 году"),
            new StringBuilder("1151 год"),
            new StringBuilder("1211 год"),
            new StringBuilder("Коновод"),
            new StringBuilder("Новгороде"),
            new StringBuilder("1130 год"),
            new StringBuilder("феодал"),
            new StringBuilder("Посадник"),
            new StringBuilder("совет господ"),
            new StringBuilder("Крестьяне"),
            new StringBuilder("Смерды"),
            new StringBuilder("Паломники"),
            new StringBuilder("Кочетники"),
            new StringBuilder("Изорники"),
            new StringBuilder("1465 год"),
            new StringBuilder("1264-1550 гг."),
            new StringBuilder("Владимирское"),
            new StringBuilder("XIV век"),
            new StringBuilder("1527 год"),
            new StringBuilder("Всеволод Юрьевич"),
            new StringBuilder("1238 год"),
            new StringBuilder("1232 год"),
            new StringBuilder("1241 год"),
            new StringBuilder("1253 год"),
            new StringBuilder("1301 год"),
            new StringBuilder("1294 год"),
            new StringBuilder("Иван III"),
            new StringBuilder("1390 год"),
            new StringBuilder("1387 год"),
            new StringBuilder("1344 год"),
            new StringBuilder("1338 год"),
            new StringBuilder("Владимир Мономах"),
            new StringBuilder("1449 год"),
            new StringBuilder("1313 год"),
            new StringBuilder("1313 год"),
            new StringBuilder("1376 год"),
            new StringBuilder("10000 рублей"),
            new StringBuilder("1370 год"),
            new StringBuilder("1369 год"),
            new StringBuilder("р. Яуза"),
            new StringBuilder("1382 год"),
            new StringBuilder("1385 год"),
            new StringBuilder("1386 год"),
            new StringBuilder("лошадь"),
            new StringBuilder("1300 год"),
            new StringBuilder("Суздаль"),
            new StringBuilder("Суздаль"),
            new StringBuilder("1445 год"),
            new StringBuilder("1461 год"),
            new StringBuilder("собрание"),
            new StringBuilder("Ловчий"),
            new StringBuilder("Конюший"),
            new StringBuilder("Ловчий"),
            new StringBuilder("Ловчий"),
            new StringBuilder("Дворянин"),
            new StringBuilder("Думный дворянин"),
            new StringBuilder("военачальник"),
            new StringBuilder("Думный дворянин"),
            new StringBuilder("Охраняли дом"),
            new StringBuilder("Ключник"),
            new StringBuilder("Казна"),
            new StringBuilder("Гектар"),
            new StringBuilder("дружинники"),
            new StringBuilder("перевозчики"),
            new StringBuilder("Тиун"),
            new StringBuilder("Тиун"),
            new StringBuilder("Тиун"),
            new StringBuilder("Рында"),
            new StringBuilder("Стольник"),
            new StringBuilder("Стольник"),
            new StringBuilder("Кравчий"),
            new StringBuilder("Ясельничий"),
            new StringBuilder("1236-1795 гг."),
            new StringBuilder("1381 год"),
            new StringBuilder("XVII"),
            new StringBuilder("1798 год"),
            new StringBuilder("1815 год"),
            new StringBuilder("Италии"),
            new StringBuilder("Архиепископ"),
            new StringBuilder("1194 год"),
            new StringBuilder("1198 год"),
            new StringBuilder("1212 год"),
            new StringBuilder("1251 год"),
            new StringBuilder("1255 год"),
            new StringBuilder("1258 год"),
            new StringBuilder("1251 год"),
            new StringBuilder("1248 год"),
            new StringBuilder("Анастасий IV"),
            new StringBuilder("1260 год"),
            new StringBuilder("1256 год"),
            new StringBuilder("1251 год"),
            new StringBuilder("1268 год"),
            new StringBuilder("Православную"),
            new StringBuilder("1311 год"),
            new StringBuilder("Наримунта"),
            new StringBuilder("1372 год"),
            new StringBuilder("1372 год"),
            new StringBuilder("1375 год"),
            new StringBuilder("1375 год"),
            new StringBuilder("1389 год"),
            new StringBuilder("1385 год"),
            new StringBuilder("1382 год"),
            new StringBuilder("1380 год"),
            new StringBuilder("1393 год"),
            new StringBuilder("1392 год"),
            new StringBuilder("1391 год"),
            new StringBuilder("Монвиду"),
            new StringBuilder("1404 год"),
            new StringBuilder("Витовта"),
            new StringBuilder("1394 год"),
            new StringBuilder("1392 год"),
            new StringBuilder("1410 год"),
            new StringBuilder("Заключают мир"),
            new StringBuilder("1406 год"),
            new StringBuilder("1402 год"),
            new StringBuilder("1421 год"),
            new StringBuilder("1427 год"),
            new StringBuilder("1420 год"),
            new StringBuilder("Венгрия"),
            new StringBuilder("Москва"),
            new StringBuilder("1432 год"),
            new StringBuilder("Ягайло"),
            new StringBuilder("1433-1435 гг."),
            new StringBuilder("1442-1444 гг."),
            new StringBuilder("1440 год"),
            new StringBuilder("Каунасе"),
            new StringBuilder("1437 год"),
            new StringBuilder("1483 год"),
            new StringBuilder("Иван III"),
            new StringBuilder("Василий II"),
            new StringBuilder("Ямато"),
            new StringBuilder("Феодал"),
            new StringBuilder("1569 год"),
            new StringBuilder("XVII веке"),
            new StringBuilder("Дзуки"),
            new StringBuilder("1599 год"),
            new StringBuilder("1595 год"),
            new StringBuilder("1592 год"),
            new StringBuilder("награждение"),
            new StringBuilder("XIII-XIV веках"),
            new StringBuilder("обычной грамотой"),
            new StringBuilder("1450 год"),
            new StringBuilder("XII век"),
            new StringBuilder("4-7"),
            new StringBuilder("XVI-XVII веках"),
            new StringBuilder("1360 год"),
            new StringBuilder("1539 год"),
            new StringBuilder("1586 год"),
            new StringBuilder("Псалтырь"),
            new StringBuilder("1512 год"),
            new StringBuilder("Владас Дубас"),
            new StringBuilder("Пятрас Браженас"),
            new StringBuilder("Франциск Скорина"),
            new StringBuilder("1516 год"),
            new StringBuilder("Максим Смотрицкий"),
            new StringBuilder("1571 год"),
            new StringBuilder("Иван Федоров"),
            new StringBuilder("1567 год"),
            new StringBuilder("Владас Дубас"),
            new StringBuilder("Пятрас Браженас"),
            new StringBuilder("1547 год"),
            new StringBuilder("XV век"),
            new StringBuilder("Пятрас Браженас"),
            new StringBuilder("1606 год"),
            new StringBuilder("Константинас Сирвидас"),
            new StringBuilder("1622 год"),
            new StringBuilder("12000 слов"),
            new StringBuilder("Ваянг"),
            new StringBuilder("Федору Ярославичу"),
            new StringBuilder("Андрей Ярославич"),
            new StringBuilder("1126 г."),
            new StringBuilder("1124 г."),
            new StringBuilder("Волжских булгар"),
            new StringBuilder("1121 г."),
            new StringBuilder("1148 г."),
            new StringBuilder("1140 г."),
            new StringBuilder("1135 г."),
            new StringBuilder("1133 г."),
            new StringBuilder("Киев"),
            new StringBuilder("Борисоглебск"),
            new StringBuilder("Переславль"),
            new StringBuilder("1150 г."),
            new StringBuilder("1137 г."),
            new StringBuilder("1151 г."),
            new StringBuilder("1151 г."),
            new StringBuilder("1147 г."),
            new StringBuilder("1141 г."),
            new StringBuilder("дочь хана Тугоркана"),
            new StringBuilder("8"),
            new StringBuilder("Ефимия"),
            new StringBuilder("2"),
            new StringBuilder("8"),
            new StringBuilder("1149-1151 гг."),
            new StringBuilder("1148-1154 гг."),
            new StringBuilder("1137 г."),
            new StringBuilder("Киев"),
            new StringBuilder("1196-1252 гг."),
            new StringBuilder("1200-1208 и 1209-1211 гг."),
            new StringBuilder("1218-1226 гг."),
            new StringBuilder("1228-1241 гг."),
            new StringBuilder("1238-1246 гг."),
            new StringBuilder("1242-1250 гг."),
            new StringBuilder("Болеслав"),
            new StringBuilder("1218 г."),
            new StringBuilder("1216 г."),
            new StringBuilder("1215 г."),
            new StringBuilder("1210 г."),
            new StringBuilder("1228 г."),
            new StringBuilder("1226 г."),
            new StringBuilder("1226-1231 гг."),
            new StringBuilder("Киеве"),
            new StringBuilder("1241 г."),
            new StringBuilder("1248 г."),
            new StringBuilder("1244 г."),
            new StringBuilder("Маммалиолит"),
            new StringBuilder("Елена"),
            new StringBuilder("1"),
            new StringBuilder("1244-1249 гг."),
            new StringBuilder("1251-1255 гг."),
            new StringBuilder("1249 г."),
            new StringBuilder("1247 г."),
            new StringBuilder("1246 г."),
            new StringBuilder("1249 г."),
            new StringBuilder("1268-1281 гг."),
            new StringBuilder("1268 г."),
            new StringBuilder("1264 г."),
            new StringBuilder("1261 г."),
            new StringBuilder("1253-1302 гг."),
            new StringBuilder("1279-1305 гг."),
            new StringBuilder("1296 г."),
            new StringBuilder("4"),
            new StringBuilder("1315 г."),
            new StringBuilder("1328-1331 гг."),
            new StringBuilder("1315 г."),
            new StringBuilder("1291-1343 гг."),
            new StringBuilder("1333-1348 гг."),
            new StringBuilder("1341 г."),
            new StringBuilder("1345 г."),
            new StringBuilder("Агафья"),
            new StringBuilder("София"),
            new StringBuilder("6"),
            new StringBuilder("1318-1380 гг."),
            new StringBuilder("1356-1355 гг."),
            new StringBuilder("1365-1388 гг."),
            new StringBuilder("1360-1363 гг."),
            new StringBuilder("Князь"),
            new StringBuilder("Торговец"),
            new StringBuilder("Симмахия"),
            new StringBuilder("Протекторат"),
            new StringBuilder("Протекторат"),
            new StringBuilder("Симмахия"),
            new StringBuilder("Симмахия"),
            new StringBuilder("Вассальное"),
            new StringBuilder("Протекторат"),
            new StringBuilder("1394 г."),
            new StringBuilder("1800 г."),
            new StringBuilder("1404 г."),
            new StringBuilder("1396 г."),
            new StringBuilder("1397 г."),
            new StringBuilder("1803 г."),
            new StringBuilder("Район"),
            new StringBuilder("Ферма"),
            new StringBuilder("1384 г."),
            new StringBuilder("1799 г."),
            new StringBuilder("1471 г."),
            new StringBuilder("1788 г."),
            new StringBuilder("1493 г."),
            new StringBuilder("1799 г."),
            new StringBuilder("1507 г."),
            new StringBuilder("1890 г."),
            new StringBuilder("1512 г."),
            new StringBuilder("1777 г."),
            new StringBuilder("1508 г."),
            new StringBuilder("1787 г."),
            new StringBuilder("1504 г."),
            new StringBuilder("1799 г."),
            new StringBuilder("1566 г."),
            new StringBuilder("1790 г."),
            new StringBuilder("1552 г."),
            new StringBuilder("1803 г."),
            new StringBuilder("1566 г."),
            new StringBuilder("1788 г."),
            new StringBuilder("1529 г."),
            new StringBuilder("1802 г."),
            new StringBuilder("1566 г."),
            new StringBuilder("1767 г."),
            new StringBuilder("1594 г."),
            new StringBuilder("1781 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1789 г."),
            new StringBuilder("1781 г."),
            new StringBuilder("1802 г."),
            new StringBuilder("1793 г."),
            new StringBuilder("1791 г."),
            new StringBuilder("1784 г."),
            new StringBuilder("1803 г."),
            new StringBuilder("1425-1453 гг."),
            new StringBuilder("1414-1425 гг."),
            new StringBuilder("1377 г."),
            new StringBuilder("1435 г."),
            new StringBuilder("1431 г."),
            new StringBuilder("Юрий Дмитриевич"),
            new StringBuilder("1415 г."),
            new StringBuilder("Евдокия Дмитриевна"),
            new StringBuilder("Василий Темный"),
            new StringBuilder("Иван Всеволож"),
            new StringBuilder("1418 г."),
            new StringBuilder("1434-1441 гг."),
            new StringBuilder("1435 г."),
            new StringBuilder("1431 г."),
            new StringBuilder("Москва"),
            new StringBuilder("1442 г."),
            new StringBuilder("Дмитрий Шемяка"),
            new StringBuilder("1431-1448 гг."),
            new StringBuilder("1439 г."),
            new StringBuilder("Москва"),
            new StringBuilder("1435/1436 г."),
            new StringBuilder("Дмитрий Шемяка"),
            new StringBuilder("Софья Витовтовна"),
            new StringBuilder("воевода Дятел"),
            new StringBuilder("Человек"),
            new StringBuilder("1441 г."),
            new StringBuilder("Дмитрий Шемяка"),
            new StringBuilder("1444 г."),
            new StringBuilder("1444 г."),
            new StringBuilder("1441 г."),
            new StringBuilder("1437 г."),
            new StringBuilder("1452 г."),
            new StringBuilder("Ослепил"),
            new StringBuilder("21000 рублей"),
            new StringBuilder("1438 г."),
            new StringBuilder("1453 г."),
            new StringBuilder("Заключение мира"),
            new StringBuilder("1447 г."),
            new StringBuilder("1446 г."),
            new StringBuilder("Разграбил")
    };

    public Question2() {}
}